#!/usr/bin/env bash
#
# Startup script: sets up and starts the Docker stack for pranavmishra.dev.
#
# It will:
#   1. Verify Docker is installed and the daemon is running (starting it if needed).
#   2. Create a .env file with sensible defaults if one does not exist.
#   3. Build the images and start the containers (db, nextjs, prisma-studio).
#
set -euo pipefail

cd "$(dirname "$0")"

# --- Colours for readable output -------------------------------------------
info()  { printf '\033[0;34m==>\033[0m %s\n' "$*"; }
ok()    { printf '\033[0;32m==>\033[0m %s\n' "$*"; }
warn()  { printf '\033[0;33m==>\033[0m %s\n' "$*"; }
die()   { printf '\033[0;31mError:\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. Ensure Docker is installed -----------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"

# Pick the compose command (plugin form preferred, legacy binary as fallback).
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose is not available (need 'docker compose' plugin or 'docker-compose')."
fi

# --- 2. Ensure the Docker daemon is running --------------------------------
if ! docker info >/dev/null 2>&1; then
  warn "Docker daemon is not running. Attempting to start it..."
  if command -v systemctl >/dev/null 2>&1; then
    sudo systemctl start docker || die "Failed to start the Docker daemon via systemctl."
    # Give the daemon a moment to come up.
    for _ in $(seq 1 10); do
      docker info >/dev/null 2>&1 && break
      sleep 1
    done
  fi
  docker info >/dev/null 2>&1 || die "Docker daemon is still not reachable. Start it manually and retry."
fi
ok "Docker daemon is running."

# --- 3. Ensure a .env file exists ------------------------------------------
if [ ! -f .env ]; then
  warn ".env not found — creating one with default development values."
  POSTGRES_USER="postgres"
  POSTGRES_PASSWORD="postgres"
  POSTGRES_DB="pranavmishra"
  cat > .env <<EOF
# Auto-generated by start.sh — edit these values for your environment.

# --- PostgreSQL (used by the "db" service in docker-compose.yml) ---
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

# Prisma / Next.js connect to the "db" service over the compose network.
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public

# --- Notion ---
# How to get: https://www.notion.so/my-integrations -> "New integration"
# -> copy the "Internal Integration Secret". Then share the page/database with
# the integration so it can read it.
NOTION_TOKEN=

# --- ImageKit (https://imagekit.io) ---
# How to get: ImageKit dashboard -> Developer options -> API Keys.
# The URL endpoint is already hard-coded in src/lib/Imagekit.ts.
IMAGEKIT_PUBLIC_KEY=
IMAGEKIT_PRIVATE_KEY=

# --- Admin ---
# How to get: choose your own password. It gates the /admin routes
# (see src/middleware.ts and src/app/api/auth/login/route.ts).
ADMIN_PASSWORD=
EOF
  ok "Created .env (default credentials — change them before any real deployment)."
else
  ok ".env found."
fi

# --- 4. Build and start the stack ------------------------------------------
info "Building images..."
$COMPOSE build

info "Starting containers..."
$COMPOSE up "$@"
